name: kermaneno_app
description: Kermaneno Application

version: 1.0.1+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  url_launcher: ^5.4.2
  http: ^0.12.0+4
  html: ^0.14.0+3
  flutter_html: ^0.11.1
  dio: ^3.0.9
  loading: ^1.0.2
  intl: ^0.16.1
  share: ^0.6.3+6
  path_provider: ^1.6.5
  sqflite: ^1.3.0
  firebase_messaging: ^6.0.13
  shared_preferences: ^0.5.6+3
  flutter_widget_from_html: ^0.3.2+2
  shamsi_date: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: assets/launcher_icon.png


flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/no-internet.png
    - assets/play-button.png
    - assets/boxed/v.png
    - assets/boxed/s.png
    - assets/boxed/k.png
    - assets/boxed/j.png
    - assets/boxed/h.png
    - assets/boxed/g.png
    - assets/boxed/f.png
    - assets/boxed/e.png


  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Bold.ttf

    - family: Vazir
      fonts:
        - asset: fonts/Vazir/Vazir-Black.ttf
          weight: 700
        - asset: fonts/Vazir/Vazir-Medium.ttf
          weight: 100

    - family: Soleil
      fonts:
        - asset: fonts/Soleil/Soleil-Bold.otf
        - asset: fonts/Soleil/Soleil-Regular.otf
